name: CI
on:
  pull_request:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    concurrency:
      group: install-${{ github.event_name }}-${{ github.head_ref }}-ubuntu-latest-node-latest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}-${{ hashFiles('frontend/package-lock.json') }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix backend && npm install --prefix frontend
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: lint-${{ github.event_name }}-${{ github.head_ref }}-ubuntu-latest-node-latest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run eslint
        run: npm run lint --prefix backend && npm run lint --prefix frontend
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: test-${{ github.event_name }}-${{ github.head_ref }}-ubuntu-latest-node-latest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run tests
        run: npm run test --prefix backend && npm run test --prefix frontend
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: build-${{ github.event_name }}-${{ github.head_ref }}-ubuntu-latest-node-latest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Attempt a build
        run: npm run build --prefix backend && npm run build --prefix frontend
  deployment_check:
    name: Deployment Check
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: deployment_check-${{ github.event_name }}-${{ github.head_ref }}-ubuntu-latest-node-latest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Attempt a build
        run: npm run type-check && npm run clean
